var city = "Cardiff"
var message = "Welcome to \(city)!"
var score = 85
var str = "Yout Score is \(score)"
var results = "The test results are here: \(str)"
let firstName = "John"
let lastName = "Smith"
var name = "\(firstName) \(lastName)"
let weather = "windy"
var forecast = "Today's weather will be \(weather)"
let message = "Variable not found"
var alert = "Error: \(message)!"
let daysRemaining = 5
var result = "\(daysRemaining) days to go"
let years = 10
var warning = "You need to be \(years) or older"
let name = "Paul"
var greeting = "Hello, \(name)!"
